Version 0.2.0 Chamgement de nom couplings -> cwipi

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -427,7 +427,7 @@ PACKAGE_VERSION='0.0.1'
 PACKAGE_STRING='fvm 0.0.1'
 PACKAGE_BUGREPORT='eric.quemerais@onera.fr'
 
-ac_unique_file="src/couplings.h"
+ac_unique_file="src/cwipi.h"
 # Factoring default headers for most tests.
 ac_includes_default="\
 #include <stdio.h>
@@ -2124,26 +2124,26 @@ am__tar='${AMTAR} chof - "$$tardir"'; am__untar='${AMTAR} xf -'
 
 
 # First arg is output file name
-if test "couplings_config.h" = "" ; then
-  couplings_ac_config_publ_h="config_publ.h"
+if test "cwipi_config.h" = "" ; then
+  cwipi_ac_config_publ_h="config_publ.h"
 else
-  couplings_ac_config_publ_h=couplings_config.h
+  cwipi_ac_config_publ_h=cwipi_config.h
 fi
-couplings_ac_lower='abcdefghijklmnopqrstuvwxyz.'
-couplings_ac_upper='ABCDEFGHIJKLMNOPQRSTUVWXYZ_'
-couplings_ac_config_publ_upname=`echo $couplings_ac_config_publ_h | sed y/$couplings_ac_lower/$couplings_ac_upper/`
-unset couplings_ac_lower
-unset couplings_ac_upper
-echo "#ifndef __"${couplings_ac_config_publ_upname}"__" >  "$couplings_ac_config_publ_h"-tmp
-echo "#define __"${couplings_ac_config_publ_upname}"__" >> "$couplings_ac_config_publ_h"-tmp
-echo >> "$couplings_ac_config_publ_h"-tmp
-echo "/* $couplings_ac_config_publ_h. Generated by configure */" >> "$couplings_ac_config_publ_h"-tmp
-echo >> "$couplings_ac_config_publ_h"-tmp
+cwipi_ac_lower='abcdefghijklmnopqrstuvwxyz.'
+cwipi_ac_upper='ABCDEFGHIJKLMNOPQRSTUVWXYZ_'
+cwipi_ac_config_publ_upname=`echo $cwipi_ac_config_publ_h | sed y/$cwipi_ac_lower/$cwipi_ac_upper/`
+unset cwipi_ac_lower
+unset cwipi_ac_upper
+echo "#ifndef __"${cwipi_ac_config_publ_upname}"__" >  "$cwipi_ac_config_publ_h"-tmp
+echo "#define __"${cwipi_ac_config_publ_upname}"__" >> "$cwipi_ac_config_publ_h"-tmp
+echo >> "$cwipi_ac_config_publ_h"-tmp
+echo "/* $cwipi_ac_config_publ_h. Generated by configure */" >> "$cwipi_ac_config_publ_h"-tmp
+echo >> "$cwipi_ac_config_publ_h"-tmp
 
-{ echo "$as_me:$LINENO: initializing $couplings_ac_config_publ_h" >&5
-echo "$as_me: initializing $couplings_ac_config_publ_h" >&6;}
+{ echo "$as_me:$LINENO: initializing $cwipi_ac_config_publ_h" >&5
+echo "$as_me: initializing $cwipi_ac_config_publ_h" >&6;}
 
-#COUPLINGS_AC_CONFIG_PUBL_VERBATIM([couplings_licence_c_comment])
+#CWIPI_AC_CONFIG_PUBL_VERBATIM([cwipi_licence_c_comment])
 
 echo "$as_me:$LINENO: checking whether to enable maintainer-specific portions of Makefiles" >&5
 echo $ECHO_N "checking whether to enable maintainer-specific portions of Makefiles... $ECHO_C" >&6
@@ -2175,50 +2175,50 @@ fi
 
 
 
-unset couplings_ac_lower
-unset couplings_ac_upper
+unset cwipi_ac_lower
+unset cwipi_ac_upper
 if test "Complete version number" != "" ; then
-  echo "/* Complete version number */" >> "$couplings_ac_config_publ_h"-tmp
+  echo "/* Complete version number */" >> "$cwipi_ac_config_publ_h"-tmp
 fi
-echo '#define COUPLINGS_VERSION "0.0.1"' >> "$couplings_ac_config_publ_h"-tmp
-echo >> "$couplings_ac_config_publ_h"-tmp
+echo '#define CWIPI_VERSION "0.0.1"' >> "$cwipi_ac_config_publ_h"-tmp
+echo >> "$cwipi_ac_config_publ_h"-tmp
 
 
 
 
 
 
-unset couplings_ac_lower
-unset couplings_ac_upper
+unset cwipi_ac_lower
+unset cwipi_ac_upper
 if test "Major version number" != "" ; then
-  echo "/* Major version number */" >> "$couplings_ac_config_publ_h"-tmp
+  echo "/* Major version number */" >> "$cwipi_ac_config_publ_h"-tmp
 fi
-echo "#define COUPLINGS_MAJOR_VERSION 0" >> "$couplings_ac_config_publ_h"-tmp
-echo >> "$couplings_ac_config_publ_h"-tmp
+echo "#define CWIPI_MAJOR_VERSION 0" >> "$cwipi_ac_config_publ_h"-tmp
+echo >> "$cwipi_ac_config_publ_h"-tmp
 
 
 
 
 
-unset couplings_ac_lower
-unset couplings_ac_upper
+unset cwipi_ac_lower
+unset cwipi_ac_upper
 if test "Minor version number" != "" ; then
-  echo "/* Minor version number */" >> "$couplings_ac_config_publ_h"-tmp
+  echo "/* Minor version number */" >> "$cwipi_ac_config_publ_h"-tmp
 fi
-echo "#define COUPLINGS_MINOR_VERSION 0" >> "$couplings_ac_config_publ_h"-tmp
-echo >> "$couplings_ac_config_publ_h"-tmp
+echo "#define CWIPI_MINOR_VERSION 0" >> "$cwipi_ac_config_publ_h"-tmp
+echo >> "$cwipi_ac_config_publ_h"-tmp
 
 
 
 
 
-unset couplings_ac_lower
-unset couplings_ac_upper
+unset cwipi_ac_lower
+unset cwipi_ac_upper
 if test "Release version number" != "" ; then
-  echo "/* Release version number */" >> "$couplings_ac_config_publ_h"-tmp
+  echo "/* Release version number */" >> "$cwipi_ac_config_publ_h"-tmp
 fi
-echo "#define COUPLINGS_RELEASE_VERSION 1" >> "$couplings_ac_config_publ_h"-tmp
-echo >> "$couplings_ac_config_publ_h"-tmp
+echo "#define CWIPI_RELEASE_VERSION 1" >> "$cwipi_ac_config_publ_h"-tmp
+echo >> "$cwipi_ac_config_publ_h"-tmp
 
 
 
@@ -18997,13 +18997,13 @@ if test "x$auto_flags" = "xtrue" ; then
 
   # Source associated recommended compiler options
 
-  if test -f "$srcdir/config/couplings_auto_flags.sh" ; then
-    { echo "$as_me:$LINENO: sourcing config/couplings_auto_flags.sh (test for known compilers)" >&5
-echo "$as_me: sourcing config/couplings_auto_flags.sh (test for known compilers)" >&6;}
-    . "$srcdir/config/couplings_auto_flags.sh"
+  if test -f "$srcdir/config/cwipi_auto_flags.sh" ; then
+    { echo "$as_me:$LINENO: sourcing config/cwipi_auto_flags.sh (test for known compilers)" >&5
+echo "$as_me: sourcing config/cwipi_auto_flags.sh (test for known compilers)" >&6;}
+    . "$srcdir/config/cwipi_auto_flags.sh"
   else
-    { echo "$as_me:$LINENO: WARNING: config/couplings_auto_flags.sh default configuration file not found" >&5
-echo "$as_me: WARNING: config/couplings_auto_flags.sh default configuration file not found" >&2;}
+    { echo "$as_me:$LINENO: WARNING: config/cwipi_auto_flags.sh default configuration file not found" >&5
+echo "$as_me: WARNING: config/cwipi_auto_flags.sh default configuration file not found" >&2;}
   fi
 
   if test "x$user_CPPFLAGS" = "x"; then
@@ -19084,7 +19084,7 @@ fi
 # take effect whether the result is true or not (maybe due to a bug),
 # so we directly use autoconf's enable_shared variable.
 
-if test "x$couplings_disable_shared" = "xyes" ; then
+if test "x$cwipi_disable_shared" = "xyes" ; then
   enable_shared=no
 fi
 
@@ -21775,17 +21775,17 @@ unset saved_LIBS
 # First arg is variable name, second arg is value, optional third arg is comment
 
 
-unset couplings_ac_lower
-unset couplings_ac_upper
-if test "couplings library configured with MPI support ?" != "" ; then
-  echo "/* couplings library configured with MPI support ? */" >> "$couplings_ac_config_publ_h"-tmp
+unset cwipi_ac_lower
+unset cwipi_ac_upper
+if test "cwipi library configured with MPI support ?" != "" ; then
+  echo "/* cwipi library configured with MPI support ? */" >> "$cwipi_ac_config_publ_h"-tmp
 fi
 if test "$have_mpi" = "yes" ; then
-  echo "#define HAVE_MPI 1" >> "$couplings_ac_config_publ_h"-tmp
+  echo "#define HAVE_MPI 1" >> "$cwipi_ac_config_publ_h"-tmp
 else
-  echo "#undef HAVE_MPI" >> "$couplings_ac_config_publ_h"-tmp
+  echo "#undef HAVE_MPI" >> "$cwipi_ac_config_publ_h"-tmp
 fi
-echo >> "$couplings_ac_config_publ_h"-tmp
+echo >> "$cwipi_ac_config_publ_h"-tmp
 
 
 if test "x$have_mpi" = "xyes" ; then
@@ -21794,17 +21794,17 @@ if test "x$have_mpi" = "xyes" ; then
 # First arg is variable name, second arg is value, optional third arg is comment
 
 
-unset couplings_ac_lower
-unset couplings_ac_upper
-if test "couplings library configured with MPI IO support ?" != "" ; then
-  echo "/* couplings library configured with MPI IO support ? */" >> "$couplings_ac_config_publ_h"-tmp
+unset cwipi_ac_lower
+unset cwipi_ac_upper
+if test "cwipi library configured with MPI IO support ?" != "" ; then
+  echo "/* cwipi library configured with MPI IO support ? */" >> "$cwipi_ac_config_publ_h"-tmp
 fi
 if test "$have_mpi_io" = "yes" ; then
-  echo "#define HAVE_MPI_IO 1" >> "$couplings_ac_config_publ_h"-tmp
+  echo "#define HAVE_MPI_IO 1" >> "$cwipi_ac_config_publ_h"-tmp
 else
-  echo "#undef HAVE_MPI_IO" >> "$couplings_ac_config_publ_h"-tmp
+  echo "#undef HAVE_MPI_IO" >> "$cwipi_ac_config_publ_h"-tmp
 fi
-echo >> "$couplings_ac_config_publ_h"-tmp
+echo >> "$cwipi_ac_config_publ_h"-tmp
 
 
 
@@ -21812,17 +21812,17 @@ echo >> "$couplings_ac_config_publ_h"-tmp
 # First arg is variable name, second arg is value, optional third arg is comment
 
 
-unset couplings_ac_lower
-unset couplings_ac_upper
-if test "couplings library configured with MPI One-sided support ?" != "" ; then
-  echo "/* couplings library configured with MPI One-sided support ? */" >> "$couplings_ac_config_publ_h"-tmp
+unset cwipi_ac_lower
+unset cwipi_ac_upper
+if test "cwipi library configured with MPI One-sided support ?" != "" ; then
+  echo "/* cwipi library configured with MPI One-sided support ? */" >> "$cwipi_ac_config_publ_h"-tmp
 fi
 if test "$have_mpi_one_sided" = "yes" ; then
-  echo "#define HAVE_MPI_ONE_SIDED 1" >> "$couplings_ac_config_publ_h"-tmp
+  echo "#define HAVE_MPI_ONE_SIDED 1" >> "$cwipi_ac_config_publ_h"-tmp
 else
-  echo "#undef HAVE_MPI_ONE_SIDED" >> "$couplings_ac_config_publ_h"-tmp
+  echo "#undef HAVE_MPI_ONE_SIDED" >> "$cwipi_ac_config_publ_h"-tmp
 fi
-echo >> "$couplings_ac_config_publ_h"-tmp
+echo >> "$cwipi_ac_config_publ_h"-tmp
 
 
 fi
@@ -22108,17 +22108,17 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 # First arg is variable name, second arg is value, optional third arg is comment
 
 
-unset couplings_ac_lower
-unset couplings_ac_upper
-if test "couplings library configured with METIS support ?" != "" ; then
-  echo "/* couplings library configured with METIS support ? */" >> "$couplings_ac_config_publ_h"-tmp
+unset cwipi_ac_lower
+unset cwipi_ac_upper
+if test "cwipi library configured with METIS support ?" != "" ; then
+  echo "/* cwipi library configured with METIS support ? */" >> "$cwipi_ac_config_publ_h"-tmp
 fi
 if test "$have_metis" = "yes" ; then
-  echo "#define HAVE_METIS 1" >> "$couplings_ac_config_publ_h"-tmp
+  echo "#define HAVE_METIS 1" >> "$cwipi_ac_config_publ_h"-tmp
 else
-  echo "#undef HAVE_METIS" >> "$couplings_ac_config_publ_h"-tmp
+  echo "#undef HAVE_METIS" >> "$cwipi_ac_config_publ_h"-tmp
 fi
-echo >> "$couplings_ac_config_publ_h"-tmp
+echo >> "$cwipi_ac_config_publ_h"-tmp
 
 
 
@@ -22179,13 +22179,13 @@ done
 
 
 # First arg is output file name
-if test "couplings-config" = "" ; then
-  couplings_ac_config_info="couplings-config"
+if test "cwipi-config" = "" ; then
+  cwipi_ac_config_info="cwipi-config"
 else
-  couplings_ac_config_info=couplings-config
+  cwipi_ac_config_info=cwipi-config
 fi
 
-outfile="$couplings_ac_config_info"-tmp
+outfile="$cwipi_ac_config_info"-tmp
 
   cat > $outfile <<\_______EOF
 #!/bin/sh
@@ -22193,15 +22193,15 @@ outfile="$couplings_ac_config_info"-tmp
 # This file is generated by the configure script.
 _______EOF
 
-{ echo "$as_me:$LINENO: initializing $couplings_ac_config_info" >&5
-echo "$as_me: initializing $couplings_ac_config_info" >&6;}
+{ echo "$as_me:$LINENO: initializing $cwipi_ac_config_info" >&5
+echo "$as_me: initializing $cwipi_ac_config_info" >&6;}
 
 
 
 
 
 
-outfile="$couplings_ac_config_info"-tmp
+outfile="$cwipi_ac_config_info"-tmp
 
 echo "
 # use debugging code:                         "$debug"
@@ -22213,14 +22213,14 @@ echo "
 
 
 
-outfile="$couplings_ac_config_info"-tmp
+outfile="$cwipi_ac_config_info"-tmp
 
-if test "${couplings_ac_cc_version}" != "" -o "${couplings_ac_cc_version_full}" != "" ; then
+if test "${cwipi_ac_cc_version}" != "" -o "${cwipi_ac_cc_version_full}" != "" ; then
   echo "" >> $outfile
-  echo "# C compiler used for build: ${couplings_ac_cc_version}" >> $outfile
+  echo "# C compiler used for build: ${cwipi_ac_cc_version}" >> $outfile
   echo "# --------------------------"    >> $outfile
-  if test "${couplings_ac_cc_version_full}" != "" ; then
-    echo "${couplings_ac_cc_version_full}" | sed 's/^/# /' >> $outfile
+  if test "${cwipi_ac_cc_version_full}" != "" ; then
+    echo "${cwipi_ac_cc_version_full}" | sed 's/^/# /' >> $outfile
   fi
   echo "" >> $outfile
 else
@@ -22235,7 +22235,7 @@ echo "" >> $outfile
 
 
 
-outfile="$couplings_ac_config_info"-tmp
+outfile="$cwipi_ac_config_info"-tmp
 
 echo ""                  >> $outfile
 echo "# Package Version" >> $outfile
@@ -22250,7 +22250,7 @@ echo "" >> $outfile
 
 
 
-outfile="$couplings_ac_config_info"-tmp
+outfile="$cwipi_ac_config_info"-tmp
 
 echo ""                           >> $outfile
 echo "# Installation directories" >> $outfile
@@ -22272,10 +22272,10 @@ echo "" >> $outfile
 
 
 
-outfile="$couplings_ac_config_info"-tmp
+outfile="$cwipi_ac_config_info"-tmp
 
 if test "" != "" ; then
-  couplings_ac_config_info_scope="${couplings_ac_config_info_scope} "
+  cwipi_ac_config_info_scope="${cwipi_ac_config_info_scope} "
   scope_prefix="_"
 else
   scope_prefix=""
@@ -22293,10 +22293,10 @@ echo "" >> $outfile
 
 
 
-outfile="$couplings_ac_config_info"-tmp
+outfile="$cwipi_ac_config_info"-tmp
 
 if test "build" != "" ; then
-  couplings_ac_config_info_scope="${couplings_ac_config_info_scope} build"
+  cwipi_ac_config_info_scope="${cwipi_ac_config_info_scope} build"
   scope_prefix="build_"
 else
   scope_prefix=""
@@ -22314,10 +22314,10 @@ echo "" >> $outfile
 
 
 
-outfile="$couplings_ac_config_info"-tmp
+outfile="$cwipi_ac_config_info"-tmp
 
 if test "bft" != "" ; then
-  couplings_ac_config_info_scope="${couplings_ac_config_info_scope} bft"
+  cwipi_ac_config_info_scope="${cwipi_ac_config_info_scope} bft"
   scope_prefix="bft_"
 else
   scope_prefix=""
@@ -22335,10 +22335,10 @@ echo "" >> $outfile
 
 
 
-outfile="$couplings_ac_config_info"-tmp
+outfile="$cwipi_ac_config_info"-tmp
 
 if test "fvm" != "" ; then
-  couplings_ac_config_info_scope="${couplings_ac_config_info_scope} fvm"
+  cwipi_ac_config_info_scope="${cwipi_ac_config_info_scope} fvm"
   scope_prefix="fvm_"
 else
   scope_prefix=""
@@ -22356,10 +22356,10 @@ echo "" >> $outfile
 
 
 
-outfile="$couplings_ac_config_info"-tmp
+outfile="$cwipi_ac_config_info"-tmp
 
 if test "mpi" != "" ; then
-  couplings_ac_config_info_scope="${couplings_ac_config_info_scope} mpi"
+  cwipi_ac_config_info_scope="${cwipi_ac_config_info_scope} mpi"
   scope_prefix="mpi_"
 else
   scope_prefix=""
@@ -22377,7 +22377,7 @@ echo "" >> $outfile
 
 
 
-outfile="$couplings_ac_config_info"-tmp
+outfile="$cwipi_ac_config_info"-tmp
 
 cat >> $outfile <<\_______EOF
 
@@ -22438,7 +22438,7 @@ fi
 
 if test "$show_help" = "yes"; then
   cat <<EOF
-Usage: couplings-config options scope
+Usage: cwipi-config options scope
 
 Options:
         --prefix            installation path prefix
@@ -22457,7 +22457,7 @@ Scope:
         use (default)       Options required for user code
 _______EOF
 
-  for scope in $couplings_ac_config_info_scope ; do
+  for scope in $cwipi_ac_config_info_scope ; do
     if test "$scope" = "build" ; then
       echo "        build               Options used for build" >> $outfile
     else
@@ -22471,14 +22471,14 @@ EOF
 fi
 _______EOF
 
-if test "$couplings_ac_config_info_scope" != "" ; then
+if test "$cwipi_ac_config_info_scope" != "" ; then
 
   cat >> $outfile <<\_______EOF
 
 case "$scope" in
 _______EOF
 
-  for scope in $couplings_ac_config_info_scope ; do
+  for scope in $cwipi_ac_config_info_scope ; do
 
     echo "  ${scope})"                      >> $outfile
     echo "    cppflags=\$${scope}_cppflags" >> $outfile
@@ -22514,17 +22514,17 @@ fi
 
 _______EOF
 
-{ echo "$as_me:$LINENO: closing $couplings_ac_config_info" >&5
-echo "$as_me: closing $couplings_ac_config_info" >&6;}
+{ echo "$as_me:$LINENO: closing $cwipi_ac_config_info" >&5
+echo "$as_me: closing $cwipi_ac_config_info" >&6;}
 
-diff $outfile $couplings_ac_config_info > /dev/null 2>&1
+diff $outfile $cwipi_ac_config_info > /dev/null 2>&1
 if test $? -eq 0 ; then
-  { echo "$as_me:$LINENO: $couplings_ac_config_info is unchanged" >&5
-echo "$as_me: $couplings_ac_config_info is unchanged" >&6;}
+  { echo "$as_me:$LINENO: $cwipi_ac_config_info is unchanged" >&5
+echo "$as_me: $cwipi_ac_config_info is unchanged" >&6;}
   rm -f $outfile
 else
-  mv $outfile $couplings_ac_config_info
-  chmod +x $couplings_ac_config_info
+  mv $outfile $cwipi_ac_config_info
+  chmod +x $cwipi_ac_config_info
 fi
 
 
@@ -22545,22 +22545,22 @@ fi
 
 
 
-echo "#endif /* __"${couplings_ac_config_publ_upname}"__ */" >>  "$couplings_ac_config_publ_h"-tmp
+echo "#endif /* __"${cwipi_ac_config_publ_upname}"__ */" >>  "$cwipi_ac_config_publ_h"-tmp
 
-{ echo "$as_me:$LINENO: closing $couplings_ac_config_publ_h" >&5
-echo "$as_me: closing $couplings_ac_config_publ_h" >&6;}
+{ echo "$as_me:$LINENO: closing $cwipi_ac_config_publ_h" >&5
+echo "$as_me: closing $cwipi_ac_config_publ_h" >&6;}
 
-diff $couplings_ac_config_publ_h $couplings_ac_config_publ_h-tmp  > /dev/null 2>&1
+diff $cwipi_ac_config_publ_h $cwipi_ac_config_publ_h-tmp  > /dev/null 2>&1
 if test $? -eq 0 ; then
-  { echo "$as_me:$LINENO: $couplings_ac_config_publ_h  is unchanged" >&5
-echo "$as_me: $couplings_ac_config_publ_h  is unchanged" >&6;}
-  rm -f $couplings_ac_config_publ_h-tmp
+  { echo "$as_me:$LINENO: $cwipi_ac_config_publ_h  is unchanged" >&5
+echo "$as_me: $cwipi_ac_config_publ_h  is unchanged" >&6;}
+  rm -f $cwipi_ac_config_publ_h-tmp
 else
-  mv $couplings_ac_config_publ_h-tmp $couplings_ac_config_publ_h
+  mv $cwipi_ac_config_publ_h-tmp $cwipi_ac_config_publ_h
 fi
 
-unset couplings_ac_config_publ_h
-unset couplings_ac_config_publ_upname
+unset cwipi_ac_config_publ_h
+unset cwipi_ac_config_publ_upname
 
 
 
@@ -24103,6 +24103,6 @@ echo "The package has been configured. Type:"
 echo " make"
 echo " make install"
 echo
-echo "To generate and install the COUPLINGS package"
+echo "To generate and install the CWIPI package"
 echo
 
